const constants = {
  LOADING: 'LOADING',
  LOADED: 'LOADED',

  ALL_POKEMONS_FETCH_STARTED: 'ALL_POKEMONS_FETCH_STARTED',
  ALL_POKEMONS_FETCH_ERROR: 'ALL_POKEMONS_FETCH_ERROR',
  ALL_POKEMONS_FETCH_COMPLETED: 'ALL_POKEMONS_FETCH_COMPLETED',

  POKEMON_FETCH_STARTED: 'POKEMON_FETCH_STARTED',
  POKEMON_FETCH_ERROR: 'POKEMON_FETCH_ERROR',
  POKEMON_FETCH_COMPLETED: 'POKEMON_FETCH_COMPLETED',
};

export default constants;
